// Package providers is the host side of the target-provider capability
// (LOOM-178, docs/design/target-providers.md §1.9, §2): it asks a plugin
// for a machine and turns it into an ordinary managed remote target,
// with a Loomux SSH key authorized on it and a host key the host
// generated and pinned before the machine existed. It owns the
// environments rows, the lifecycle (start, stop, recreate, destroy), the
// reconcile loop and orphan cleanup. Nothing upstream of the target
// knows the difference.
package providers

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base32"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"

	"github.com/Loomux/server/plugins/protocol"
	"github.com/Loomux/server/registry"
)

// Machines are reached as user agent in /data/work (design §2.4).
const (
	WorkspaceRoot = "/data/work"
	// authorizedKeyOptions prefix the target's key in the machine's
	// authorized_keys: Loomux needs no forwarding (not no-pty: tmux does).
	authorizedKeyOptions = "no-port-forwarding,no-agent-forwarding,no-X11-forwarding"
)

// Errors the API maps to status codes.
var (
	// ErrNotMachine: the target wasn't made by a plugin.
	ErrNotMachine = errors.New("providers: the target wasn't created by a plugin")
	// ErrPluginUnavailable: the plugin that owns the machine isn't
	// installed, enabled and running.
	ErrPluginUnavailable = errors.New("providers: the plugin isn't running")
	// ErrDetached: the plugin that made the machine was uninstalled;
	// nothing manages it.
	ErrDetached = errors.New("providers: the machine's plugin was uninstalled; the machine itself must be removed by hand")
	// ErrTaskActive: a task is mid-turn or taken over on the machine.
	ErrTaskActive = errors.New("providers: a task is running on the machine; cancel it or let it finish")
	// ErrEphemeralStop: an ephemeral machine can't be stopped, only
	// destroyed.
	ErrEphemeralStop = errors.New("providers: an ephemeral machine keeps nothing when stopped; destroy it instead")
	// ErrQuota: the plugin's max_environments is reached.
	ErrQuota = errors.New("providers: the plugin's machine limit is reached")
)

// BadStateError: the operation doesn't apply to the machine's state.
type BadStateError struct {
	Op     string
	Status registry.EnvironmentStatus
}

func (e *BadStateError) Error() string {
	return fmt.Sprintf("providers: can't %s a machine that is %s", e.Op, e.Status)
}

// InvalidError: a request field the plugin's offer doesn't allow; safe
// to show.
type InvalidError struct {
	Field string
	Msg   string
}

func (e *InvalidError) Error() string { return "providers: " + e.Field + ": " + e.Msg }

// BadAddressError: a plugin returned an address the host won't connect
// to.
type BadAddressError struct{ Detail string }

func (e *BadAddressError) Error() string {
	return "providers: the plugin returned an address the host refuses: " + e.Detail
}

// newID is the short id object names derive from (lx-<id>): 10
// lowercase base32 characters from crypto/rand.
func newID() (string, error) {
	var b [7]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	enc := base32.StdEncoding.WithPadding(base32.NoPadding)
	return strings.ToLower(enc.EncodeToString(b[:]))[:10], nil
}

// hostLabel is one DNS label; the whole name is at most 253 bytes.
var hostLabel = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$`)

// validHost is the managed-mode host grammar (design, LOOM-138): an
// RFC 1123 name or an IP literal; nothing ssh could read as an option
// or a shell as syntax.
func validHost(host string) bool {
	if host == "" || len(host) > 253 || strings.HasPrefix(host, "-") {
		return false
	}
	if ip := net.ParseIP(host); ip != nil {
		return true
	}
	for _, label := range strings.Split(strings.TrimSuffix(host, "."), ".") {
		if !hostLabel.MatchString(label) {
			return false
		}
	}
	return true
}

// checkAddress refuses what the host won't connect to.
func checkAddress(a protocol.Address) error {
	if !validHost(a.Host) {
		return &BadAddressError{Detail: "host " + strconv.Quote(truncate(a.Host, 80))}
	}
	if a.Port < 1 || a.Port > 65535 {
		return &BadAddressError{Detail: fmt.Sprintf("port %d", a.Port)}
	}
	switch a.Proxy {
	case "", protocol.SSHProxyNone, protocol.SSHProxyDefault:
	default:
		return &BadAddressError{Detail: "proxy " + strconv.Quote(truncate(a.Proxy, 40))}
	}
	return nil
}

func truncate(s string, n int) string {
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

// hostKeyPair is the machine's sshd host key, generated by the host.
type hostKeyPair struct {
	privatePEM []byte // OpenSSH private key format
	public     string // "ssh-ed25519 AAAA…"
	pubKey     ssh.PublicKey
}

func generateHostKey(id string) (*hostKeyPair, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("providers: host key: %w", err)
	}
	block, err := ssh.MarshalPrivateKey(priv, "loomux-machine-"+id)
	if err != nil {
		return nil, fmt.Errorf("providers: host key: %w", err)
	}
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		return nil, fmt.Errorf("providers: host key: %w", err)
	}
	return &hostKeyPair{
		privatePEM: pem.EncodeToMemory(block),
		public:     strings.TrimSpace(string(ssh.MarshalAuthorizedKey(sshPub))),
		pubKey:     sshPub,
	}, nil
}

// pinLine is the known_hosts line pinning pub for host:port, as a
// managed target stores it (LOOM-114): "[host]:port type key" for a
// port other than 22.
func pinLine(host string, port int, pub ssh.PublicKey) string {
	addr := knownhosts.Normalize(net.JoinHostPort(host, strconv.Itoa(port)))
	return knownhosts.Line([]string{addr}, pub)
}

// parsePublicKey reads an authorized_keys-format public key.
func parsePublicKey(s string) (ssh.PublicKey, error) {
	pub, _, _, _, err := ssh.ParseAuthorizedKey([]byte(s))
	if err != nil {
		return nil, fmt.Errorf("providers: public key: %w", err)
	}
	return pub, nil
}

// authorizedKeyLine is the target's managed public key as the machine's
// authorized_keys line.
func authorizedKeyLine(k *registry.SSHKey) string {
	return authorizedKeyOptions + " " + k.PublicKey
}

// expandTemplate fills {id} in a plugin's address template.
func expandTemplate(template, id string) string {
	return strings.ReplaceAll(template, "{id}", id)
}

// ActiveTaskChecker reports whether a task on any of targetID's
// workspaces is mid-turn, taken over or waiting on a person: what
// refuses stop, recreate and destroy. For Manager.ActiveTask.
func ActiveTaskChecker(store registry.Store) func(ctx context.Context, targetID string) (bool, error) {
	return func(ctx context.Context, targetID string) (bool, error) {
		workspaces, err := store.ListWorkspaces(ctx)
		if err != nil {
			return false, err
		}
		onTarget := map[string]bool{}
		for _, ws := range workspaces {
			if ws.TargetID == targetID {
				onTarget[ws.ID] = true
			}
		}
		if len(onTarget) == 0 {
			return false, nil
		}
		tasks, err := store.ListTasks(ctx)
		if err != nil {
			return false, err
		}
		for _, t := range tasks {
			if !onTarget[t.WorkspaceID] {
				continue
			}
			switch t.Status {
			case registry.TaskStatusRunning, registry.TaskStatusHumanTakeover, registry.TaskStatusNeedsAttention:
				return true, nil
			}
		}
		return false, nil
	}
}
